### ISSUE TITLE
CSP blocks javascript

### ISSUE THREAD

**Issue by kungfoolfighting** [sonst-was/simpleTwo#2]
Hello!
On my website using this theme inside the pico plugin for Nextcloud I get errors in chrome when accessing the website:
`Refused to load the script 'http://code.jquery.com/jquery-latest.min.js' because it violates the following Content Security Policy directive: "script-src 'nonce-Y3ZZZFlSRGk0MEVkc2dIT2E4c3RKcS9lVkx2T1oybG44T3pMNUJPUFpsQT06SjcxRUtFYUZ1eUJyd3plS1hLTkhDZUc3TlpTTEhoRklnSUQ2cG1MT0RnUT0=' 'unsafe-eval'". `

I know this is related to the next cloud CSP settings and not directly related to this theme, but I was hoping you would be able to help me.
I am running Nextcloud in a docker container that uses nginx.

Any help would be very welcome.
Cheers

**Comment by sonst-was** [comment]
Thanks for the report :)

I think I know where this error might come from. I'm currently at work and can't test it. I'll have a look this afternoon.

**Comment by kungfoolfighting** [comment]
I was able to get rid of the error with an ugly hack:
I added a url rewrite and a proxy_pass in the nginx configuration. Then I also added a proxy_hide_header directive for the CSP header.
Then I rewrote every link in the theme so that it no longer uses the page.url but rather my new redirected url and page.id. Now every link uses the redirected and proxied url that clears the header from the Nextcloud header.
This is very ugly, sadly but I have not found out how else to fix it.

**Comment by sonst-was** [comment]
The solution I've found was replacing the remote jQuery version [in the index.html (line 9)](https://github.com/sonst-was/simpleTwo/blob/451926e184f31d6db26dc54b813e9bccc0ad0451/index.html#L9) with a local version. I wasn't able to try it yesterday (hopefully today), but you could try to copy jQuery to the `/js/` folder and change the code in line 9 to the following:
`	<script src="{{ theme_url }}/js/jquery-latest.min.js"></script>` (maybe you need to adjust the jQuery file name depending on the version you downloaded).

This is what I'll try this evening, but first I have to get pico into my nextcloud.

**Comment by kungfoolfighting** [comment]
Cool thanks for working on this. Did you really get this to work in pico_cms plugin for nextcloud? I resorted to pulling jquery to the server too, but it would still complain about locally executing scripts without a nonce.
